Repository wecode-bootcamp-korea/18-2nd-WHATTHEPEDIA-frontend, pull requests merged in 2021-04, with the labels that each got.

#1 [18기 강준우] Add: footer 초기 레이아웃 리뷰 반영 완료
  package-lock.json
  package.json
  src/Components/Footer/Footer.js
  src/Components/PublicFooter/Components/Address.js
  src/Components/PublicFooter/Components/TotalAssess.js
  src/Components/PublicFooter/PublicFooter.js
  src/Routes.js
Labels: Status: Accepted

#2 [18기 남궁선아] 네비게이션바 레이아웃 완료, 리팩토링 완료
  .env
  package-lock.json
  package.json
  public/favicon.ico
  public/images/logo.png
  public/images/logo_white.png
  public/images/userprofile.png
  public/index.html
  src/Components/Modal/Modal.js
  src/Components/Nav/Login/Login.js
  src/Components/Nav/Login/Logout.js
  src/Components/Nav/Nav.js
  src/Pages/Main/Main.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#7 [18기 강준우] 최종 내 평가페이지
  public/data/MyMovie.json
  public/images/watthe_label.png
  src/Pages/Movie/Movie.js
  src/Pages/MyRating/Components/Modal.js
  src/Pages/MyRating/Components/Movie.js
  src/Pages/MyRating/Components/MovieList.js
  src/Pages/MyRating/Components/MyNav.js
  src/Pages/MyRating/MyRating.js
  src/Routes.js
Labels: Status: 리뷰 요청

#6 [18기 남궁선아] 모달창 로그인/회원가입 자체 로그인 구현완료, 카카오 소셜로그인 구현완료, nav바 연결 완료
  public/images/kakaologin.png
  public/images/kakaosymbol.png
  src/Components/Button/Button.js
  src/Components/Form/Form.js
  src/Components/Form/FormLayout.js
  src/Components/Input/Input.js
  src/Components/Modal/Modal.js
  src/Components/Nav/Login/KakaoLogin.js
  src/Components/Nav/Login/Login.js
  src/Components/Nav/Nav.js
  src/Components/PublicFooter/PublicFooter.js
  src/Pages/Main/Main.js
  src/Styles/globalStyle.js
  src/config.js
Labels: Status: 리뷰진행중

#5 [18기 강준우] 최종 메인페이지
  public/data/MovieData.json
  public/data/MovieData2.json
  src/Components/PublicFooter/Components/TotalAssess.js
  src/Components/PublicFooter/PublicFooter.js
  src/Pages/Main/Components/MovieList.js
  src/Pages/Main/Components/Movies.js
  src/Pages/Main/Main.js
  src/Pages/MyPage/MyPage.js
  src/Pages/MyRating/Components/Movie.js
  src/Pages/MyRating/Components/MovieList.js
  src/Pages/Review/Review.js
  src/Routes.js
Labels: Status: 리뷰 요청

#8 [18기 남궁선아] 마이페이지 메인 구현 완료, API 통신 완료
  public/data/MypageData.json
  public/images/sampleimg7.jpg
  src/Components/Nav/Nav.js
  src/Pages/MyPage/MyPage.js
  src/Styles/globalStyle.js
  src/config.js
Labels: Status: 리뷰 요청

#9 [18기 남궁선아] nav바 검색모달창 구현완료
  public/data/SearchData.json
  src/Components/Modal/Modal.js
  src/Components/Nav/Nav.js
  src/Components/Nav/SearchModal/SearchModal.js
  src/Pages/MyRating/MyRating.js
  src/config.js
Labels: Status: Accepted

#3 [18기 김우영] 상세페이지 최종구현 완료
  package-lock.json
  package.json
  public/data/movieDetail.json
  public/images/actor.jpg
  public/images/movieDetail.jpg
  public/images/movieName.jpg
  public/images/readme.md
  src/Components/PublicFooter/Components/TotalAssess.js
  src/Pages/Movie/Feed.js
  src/Pages/Movie/Feed/Modal.js
  src/Pages/Movie/Feed/ModalContent.js
  src/Pages/Movie/Feed/MovieInfo.js
  src/Pages/Movie/Feed/Rating.js
  src/Pages/Movie/Feed/Utility.js
  src/Pages/Movie/Gallery.js
  src/Pages/Movie/Information.js
  src/Pages/Movie/Information/Actor.js
  src/Pages/Movie/Information/ActorInfo.js
  src/Pages/Movie/Information/BasicInfo.js
  src/Pages/Movie/Information/Comment.js
  src/Pages/Movie/Information/Graph.js
  src/Pages/Movie/Information/SameMovie.js
  src/Pages/Movie/Movie.js
  src/config.js
Labels: Status: 리뷰 요청
